### ISSUE TITLE
create Makefile to build bagit lambda

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/cgp-dashboard-service#65] opened 2018-04-03 14:39 UTC
relates to #https://github.com/DataBiosphere/bagit-firecloud-lambda/issues/2

**Comment by coverbeck** [comment] 2018-04-13 16:55
This looks like a duplicate of DataBiosphere/bagit-firecloud-lambda#2

**Comment by mikebaumann** [comment] 2018-04-24 16:33
Closing, as this is a duplicate of DataBiosphere/bagit-firecloud-lambda#2

**Closed** 2018-04-30 21:05 UTC
Labels: Boardwalk to FireCloud integration, in progress
